name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que deseja usar para deploy

  workflow_dispatch:  # Permite rodar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v3

      - name: Fazer upload dos arquivos para o GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Pega todos os arquivos do repositório

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v2
